# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
warnings_are_errors: false

os:
  - linux
  - osx

r:
  - 3.5
  - release
  - devel

matrix:
  exclude:
    - r: devel
      os: osx
